services:
  reverse-proxy:
    image: traefik
    restart: 'unless-stopped'
    volumes:
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    restart: 'unless-stopped'
    volumes:
      - ./configs/apps/auth.yml:/config/config.yml
      - ./apps/auth:/app/apps/auth
    labels:
       - service=auth
       - traefik.enable=true
       - traefik.http.services.auth.loadbalancer.server.port=8080
       - traefik.http.routers.auth.entrypoints=websecure
       - traefik.http.routers.auth.rule=Host(`auth.localhost`)
       - traefik.http.routers.auth.tls=true
    depends_on:
      - auth-database
      - auth-cache

  auth-database:
    image: postgres
    volumes:
      - auth-database-data:/var/lib/postgresql
    restart: 'unless-stopped'
    environment:
      - POSTGRES_USER=${AUTH_DATABASE_USER}
      - POSTGRES_PASSWORD=${AUTH_DATABASE_PASSWORD}
      - POSTGRES_DB=${AUTH_DATABASE_NAME}

  auth-cache:
    image: redis
    restart: 'unless-stopped'
    volumes:
      - auth-cache-data:/data

  device:
    build:
      context: .
      dockerfile: ./apps/device/Dockerfile
    restart: 'unless-stopped'
    volumes:
      - ./configs/apps/device.yml:/config/config.yml
      - ./apps/device:/app/apps/device
    labels:
      - service=device
      - traefik.enable=true

  ingest:
    build:
      context: .
      dockerfile: ./apps/ingest/Dockerfile
    restart: 'unless-stopped'
    volumes:
      - ./configs/apps/ingest.yml:/config/config.yml
      - ./apps/ingest:/app/apps/ingest
    labels:
      - service=ingest
      - traefik.enable=true

  tracker:
    build:
      context: .
      dockerfile: ./apps/tracker/Dockerfile
    restart: 'unless-stopped'
    volumes:
      - ./configs/apps/tracker.yml:/config/config.yml
      - ./apps/tracker:/app/apps/tracker
    labels:
      - service=tracker
      - traefik.enable=true

volumes:
  auth-database-data:
  auth-cache-data:
