name: Build packages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io/${{github.repository_owner}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - auth
          - tracker
          - ingest
          - device

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/${{matrix.package}}/Dockerfile
          push: true
          tags: |
              ${{env.REGISTRY}}/${{matrix.package}}:${{github.sha}}
              ${{env.REGISTRY}}/${{matrix.package}}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
